accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('dashboard',views.dashboard,name='dashboard'),
]

bcre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls
urlpatterns = [
    path('',include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('contacts.urls')),
    path('admin/', admin.site.urls)
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + debug_toolbar_urls()

listings/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='listings'),
    path('<int:listing_id>',views.listing,name='listing'),
    path('search',views.search,name='search')
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns =[
   path("", views.index, name='index'),
   path('about', views.about, name='about')
]
    

accounts/models.py
from django.db import models

# Create your models here.

listings/models.py
from django.db import models
from realtors.models import Realtor
from datetime import datetime
from listings.choices import district_choices

class Listing(models.Model):
    realtor = models.ForeignKey(Realtor,on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    street = models.CharField(max_length=200)
    district = models.CharField(max_length=50,choices=district_choices.items())
    description = models.TextField(blank=True)
    price = models.IntegerField()
    bedrooms = models.IntegerField()
    bathrooms = models.DecimalField(max_digits=2,decimal_places=1)
    clubhouse = models.IntegerField()
    sqft = models.IntegerField()
    estate_size = models.FloatField(default=0.0)
    is_published = models.BooleanField(default=True)
    list_date = models.DateTimeField(default=datetime.now,blank=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/',blank=True)

    def __str__(self):
        return f'House Title {self.title}'

realtors/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Realtor(models.Model):
    name = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d')
    description = models.TextField(blank=True)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    is_mvp = models.BooleanField(default=False)
    hire_date = models.DateTimeField(default=datetime.now,blank=True)

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User

def register(request):
    if request.method == "POST":
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request,"username already taken.")
                return redirect('register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request,"email already taken.")
                else:
                    user = User.objects.create_user(
                        username=username,
                        password=password,
                        email=email,
                        first_name=first_name,
                        last_name=last_name
                        )
                    user.save()
                    messages.success(request,"You are now registered and can log in.")
                    return redirect('login')
        else:
            messages.error(request,"password do not match")
            return redirect("register")
    else:
        return render(request,'accounts/register.html')

def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            messages.success(request,'You are now logged in')
            return redirect('dashboard')
        else:
            messages.error(request,"Invalid Credentials")
            return redirect("login")
    else:
        return render(request,'accounts/login.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        messages.success(request, 'You are now logged out!')
    return redirect("index")
    

def dashboard(request):
    return render(request,'accounts/dashboard.html')

listings/views.py
from django.shortcuts import render
from .models import Listing
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from listings.choices import price_choices, bedroom_choices, district_choices
# Create your views here.
def index(request):
    listings = Listing.objects.order_by ('-list_date').filter(is_published=True)
    paginator = Paginator(listings,3)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)
    context = {
        'listings' : paged_listings
    }
    return render(request, 'listings/listings.html', context)
                  
def listing(request, listing_id):
    return render(request, 'listings/listing.html')

def search(request):
    queryset_list = Listing.objects.order_by('-list_date')
    if 'keywords' in request.GET:
        keywords = request.GET ['keywords']
        if keywords:
            queryset_list = queryset_list.filter(description__icontains = keywords)
    if 'title' in request.GET:
        title = request.GET['title']
        queryset_list = queryset_list.filter(title__icontains = title)
    if  'district' in request.GET:
        district = request.GET['district']
        if district != '_':
            queryset_list = queryset_list.filter(district__iexact = district)
    if  'price' in request.GET:
        price = request.GET['price']
        if price:
            queryset_list = queryset_list.filter(price__lte = price)
        
    if  'bedrooms' in request.GET:
        bedrooms = request.GET['bedrooms']
        if bedrooms:
            queryset_list = queryset_list.filter(bedrooms__lte = bedrooms)

    context = { 
        'price_choices': price_choices,
        'bedroom_choices': bedroom_choices,
        'district_choices': district_choices,
        'listing': queryset_list,
        'values': request.GET
    }
    return render(request, 'listings/search.html', context)

pages/views.py
from django.shortcuts import render
from django.http import HttpResponse
from listings.models import Listing
from realtors.models import Realtor
from listings.choices import price_choices, bedroom_choices, district_choices
# Create your views here.
def index(request):
    listings = Listing.objects.order_by('-list_date').filter(is_published=True)[:3]
    context =  {'listings': listings,
            'price_choices' : price_choices,
            'bedroom_choices': bedroom_choices,
            'district_choices' : district_choices,
            'listing':listings
            }
    return render(request, 'pages/index.html', context)
    

def about(request):
   
    realtors = Realtor.objects.order_by('-hire_date')
    mvp_realtors = Realtor.objects.all().filter(is_mvp=True)
    context = {
        'realtors' : realtors,
        'mvp_realtors' : mvp_realtors
    }
    return render(request,'pages/about.html',context)

realtors/views.py
from django.shortcuts import render

# Create your views here.

templates/_footer.html
{% if messages %}{% for message in messages %}
<div class="container" id="message">
    <div 

templates/_navbar.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
      <a class="navbar-brand" href="index.html">
        <img src="assets/img/logo.png" class="logo" alt="" />
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNavAltMarkup"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">
          <li class="nav-item mr-3">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item active mr-3">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item mr-3">
            <a class="nav-link" href="listings.html">Featured Listings</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item mr-3">
            <a class="nav-link" href="register.html">
              <i class="fas fa-user-plus"></i> Register</a
            >
          </li>
          <li class="nav-item mr-3">
            <a class="nav-link" href="login.html">
              <i class="fas fa-sign-in-alt"></i>

              Login</a
            >
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">About BC Real Estate</h1>
          <p class="lead">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
            pariatur!
          </p>
        </div>
      </div>
    </div>
  </section>



herf="javascript:{document.getElementById('logout').submit()}">
<iLogout class="fas fa-sign-out-alt"></iLogout</a>
    form action="{% url 'logout' %}"method='POST'
id="logout">
{% csrf_token %}
<input type='hidden'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href={% static "css/all.css"%} />
    <!-- Bootstrap -->
    <link rel="stylesheet" href={% static "css/bootstrap.css"%}/>
    <link rel="stylesheet" href={% static "css/style.css"%}/>
    <link rel="stylesheet" href={% static "css/lightbox.min.css"%}/> 
    
    <title>BC Real Estate {% block title %}{% endblock %}

    </title>
  </head>


  <body>
    {% include 'partials/_topbar.html'%}
    {% include 'partials/_navbar.html'%}
    {% block content %}{% endblock %}
    {% include 'partials/_footer.html' %}
    <script src={% static "js/jquery-3.3.1.min.js"%}></script>
    <script src={% static "js/bootstrap.bundle.min.js"%}></script>
    <script src={% static "js/main.js"%}></script>
    <script src={% static "js/lightbox.min.js"%}></script>
  </body>
</html>

templates/listings/listing.html
{% extends 'base.html' %} 
{% block title %} {{listing.title | title}}{%endblock %}
{% block content %}
<h1>search</h1>
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">{{listing.title | title}}</h1>
          <p class="lead"><i class="fas fa-map-marker"></i>{{listing.get_district_display}}/p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href={% url "index" %}>Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url "listings %">Listings</a>
          </li>
          <li class="breadcrumb-item active">45 Prince Street</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listing -->
  <section id="listing" class="py-4">
    <div class="container">
      <a href="listings.html" class="btn btn-light mb-4">Back To Listings</a>
      <div class="row">
        <div class="col-md-9">
          <!-- Home Main Image -->
          <img
            src="assets/img/homes/home-1.jpg"
            alt=""
            class="img-main img-fluid mb-3"
          />
          <!-- Thumbnails -->
          <div class="row mb-5 thumbs">
            {% if listing.photo_1 %}
            <div class="col-md-2">
            </div>
            {% endif %}
              <a
                href={{listing.photo_1.url}}
                data-lightbox="home-images"
              >
                <img
                  src={{listing.photo_1.url}}
                  alt=""
                  class="img-fluid"
                />
              </a>
            </div>
            
            {% if listing.photo.2 %}
            <div class="col-md-2">
            </div>
            {% endif %}
              <a
                href={{listing.photo_2.url}}
                data-lightbox="home-images"
              >
                <img
                  src={{listing.photo_2.url}}
                  alt=""
                  class="img-fluid"
                />
              </a>
            </div>
            {% if listing.photo_3 %}
            <div class="col-md-2">
            </div>
            {% endif %}
              <a
                href={{listing.photo_3.url}}
                data-lightbox="home-images"
              >
                <img
                  src={{listing.photo_3.url}}
                  alt=""
                  class="img-fluid"
                />
              </a>
            </div> {% if listing.photo_4 %}
            <div class="col-md-2">
            </div>
            {% endif %}
              <a
                href={{listing.photo_4.url}}
                data-lightbox="home-images"
              >
                <img
                  src={{listing.photo_4.url}}
                  alt=""
                  class="img-fluid"
                />
              </a>
            </div>
            {% if listing.photo_5 %}
            <div class="col-md-2">
            </div>
            {% endif %}
              <a
                href={{listing.photo_5.url}}
                data-lightbox="home-images"
              >
                <img
                  src={{listing.photo_5.url}}
                  alt=""
                  class="img-fluid"
                />
              </a>
            </div>
            {% if listing.photo_6 %}
            <div class="col-md-2">
            </div>
            {% endif %}
              <a
                href={{listing.photo_6.url}}
                data-lightbox="home-images"
              >
                <img
                  src={{listing.photo_6.url}}
                  alt=""
                  class="img-fluid"
                />
              </a>
            </div>
          </div>
          <!-- Fields -->
          <div class="row mb-5 fields">
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                  <i class="fas fa-money-bill-alt"></i> Asking Price:
                  <span class="float-right">$490,000</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bed"></i> Bedrooms:
                  <span class="float-right">3</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bath"></i> Bathrooms:
                  <span class="float-right">2</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-dumbbell"></i> ClubHouse:
                  <span class="float-right">2 </span>
                </li>
              </ul>
            </div>
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                  <i class="fas fa-th-large"></i> Square Feet:
                  <span class="float-right">3200</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-square"></i> Estate Size:
                  <span class="float-right">15 Buildings </span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-calendar"></i> Listing Date:
                  <span class="float-right">8/30/2018</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bed"></i> Realtor:
                  <span class="float-right">Kyle Chan </span>
                </li>
              </ul>
            </div>
          </div>

          <!-- Description -->
          <div class="row mb-5">
            <div class="col-md-12">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Mollitia recusandae esse reiciendis officia omnis non rerum
              dicta cupiditate nostrum molestias deserunt aut minus inventore
              animi atque, consequuntur ad fugit. Possimus culpa blanditiis
              repellendus ipsa similique ullam, natus error dolor harum.
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mb-3">
            <img
              class="card-img-top"
              src="assets/img/realtors/kyle.jpg"
              alt="Seller of the month"
            />
            <div class="card-body">
              <h5 class="card-title">Property Realtor</h5>
              <h6 class="text-secondary">Kyle Chan</h6>
            </div>
          </div>
          <button
            class="btn-primary btn-block btn-lg"
            data-toggle="modal"
            data-target="#inquiryModal"
          >
            Make An Inquiry
          </button>
        </div>
      </div>
    </div>
  </section>

  <!-- Inquiry Modal -->
  <div class="modal fade" id="inquiryModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
          <button type="button" class="close" data-dismiss="modal">
            <span>&times;</span>
          </button>
        </div>
        <div class="modal-body">
        {% comment %} modal {% endcomment %}
          <form action= "{% url 'contact %}"method= "POST">
          {% csrf_token %}
          check user then get id
          {% if user.is_authenticated %}
          <input type = "hidden"name="user_id" value={{user.id}}/>
          {% else %}

          <input type="hidden" name="user_id" value=0 />
          {% endif %}
          <input type="hidden" name="realtor_email" value={{listing.realtor.email}} />
          <input type="hidden" name="listing_id" value={{listing.id}} />

          

            <div class="form-group">
              <label for="property_name" class="col-form-label"
                >Property:</label
              >
              <input
                type="text"
                name="listing"
                class="form-control"
                value="{{listing.title}}"
                disabled
              />
            </div>
            <div class="form-group">
              <label for="name" class="col-form-label">Name:</label>
              <input type="text" name="name" class="form-control" required />
            </div>
            <div class="form-group">
              <label for="email" class="col-form-label">Email:</label>
              <input
                type="email"
                name="email"
                class="form-control" 
                <% if user.is_authenticated %}value={{user.email}}
              {{% endif %}}
                required/>
            </div>
            <div class="form-group">
              <label for="phone" class="col-form-label">Phone:</label>
              <input type="text" name="phone" class="form-control" 
              <% if user.is_authenticated %}value=" {{user.first_name}}
              {{user.last.name}}"{{% endif %}}
              />
            </div>
            <div class="form-group">
              <label for="message" class="col-form-label">Message:</label>
              <textarea name="message" class="form-control"></textarea>
            </div>
            <hr />
            <input
              type="submit"
              value="Send"
              class="btn btn-block btn-secondary"
            />
          </form>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

templates/listings/listings.html
{% extends 'base.html' %}{% load humanize %}
{% block content %}{% block title %}{% endblock content %}
    <!-- Showcase -->
    <section id="showcase-inner" class="py-2 text-white">
        <div class="container">
          <div class="row text-center">
            <div class="col-md-7">
              <h1 class="display-2">Rent or buy houses</h1>
              <p class="lead">
                United Kingdom Leeds, amet consectetur adipisicing elit. Sunt,
                pariatur!
              </p>
            </div>
          </div>
        </div>
      </section>
  
      <!-- Breadcrumb -->
      <section id="bc" class="mt-2">
        <div class="container">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <!-- correct -->
                <a href={% url "index" %}> <i class="fas fa-home"></i> At Home</a>
              </li>
              <li class="breadcrumb-item active">Find Listings</li>
            </ol>
          </nav>
        </div>
      </section>
  
      <!-- Listings -->
      <section id="listings" class="py-2">
        <div class="container">
          <div class="row">
            <!-- Listing 1 -->
            {% if listings %}
            {% for listing in listings %}
            <div class="col-md-6 col-lg-8 mb-4">
              <div class="card listing-preview">
                <!-- correct -->
                <img
                  class="card-img-top"
                  src="{{ listing.photo_main.url }}"
                  alt=""
                />
                <div class="card-img-overlay">
                  <h2>
                    <span class="badge badge-secondary text-white"
                      >${{ listing.price | intcomma }}</span
                    >
                  </h2>
                </div>
                <div class="card-body">
                  <div class="listing-heading text-center">
                    <h4 class="text-primary">{{ listing.title }}</h4>
                    <p>
                      <i class="fas fa-map-marker text-secondary"></i>{{ listing.district }}
                    </p>
                  </div>
                  <hr />
                  <div class="row py-2 text-secondary">
                    <div class="col-6">
                      <i class="fas fa-th-large"></i> Sqft:{{ listing.sqft  | intcomma }}
                    </div>
                    <div class="col-6">
                      <i class="fas fa-dumbbell"></i> ClubHouse:{{ listing.clubhouse }}
                    </div>
                  </div>
                  <div class="row py-2 text-secondary">
                    <div class="col-6">
                      <i class="fas fa-bed"></i> Bedrooms: {{ listing.bedrooms }}
                    </div>
                    <div class="col-6">
                      <i class="fas fa-bath"></i> Bathrooms: {{ listing.bathrooms }}
                    </div>
                  </div>
                  <hr />
                  <div class="row py-2 text-secondary">
                    <div class="col-12">
                      <i class="fas fa-user"></i> {{ listing.realtor }}
                    </div>
                  </div>
                  <div class="row text-secondary pb-2">
                    <div class="col-6">
                      <i class="fas fa-clock"></i> {{ listing.list_date | timesince}}
                    </div>
                  </div>
                  <hr />
                  <!-- correct -->
                  <a href={% url "listing" listing.id %}" class="btn btn-primary btn-block"
                    >More Info</a>
                </div>
              </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="col-md-12">
              <p>No Listing Available</p>
            </div>
            {% endif %}
          </div>
  
          <div class="row">
            <div class="col-md-12">
            {% if listings.has_other_pages %}
              <ul  class="pagination">
               {% if listings.has_previous %}
                <li class="page-item ">
                  <a class="page-link" href="?page={{listings.previous_page_number}}">&laquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#">&laquo;</a>
                </li>
                {% endif %}
                {% for i in listings.paginator.page_range %}
                {% if listings.number == i %}
                <li class="page-item active">
                  <a class="page-link" >{{i}}</a>
                </li>
                 {% else %}
               <li class="page-item">
                  <a class="page-link" href="?{{i}}">{{i}}</a>
                  <li>
                {% endif %}
                {% endfor %}
                {% if listings.has_next %}
                <li class="page-item">,
                  <a class="page-link" href="?page={{listings.next_page_number}}">&raquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                  <a class="page-link" herf="#">&raquo;</a>
                  </li>
                  {% endif %}
                </ul>
              {% endif %}
            </div>
          </div>
        </div>
      </section>
{% endblock %}

templates/pages/about.html
{% extends "base.html" %} {% block content %}

{% load static %}
{% block title %} | About {% endblock %}

<section id="showcase-inner" class="py-5 text-black">
  <div class="container">
    <div class="row text-center">
   
      <div class="col-md-10">
        <p>Sorry.No Realtor Available today</p>
      </div>
      

        <h1 class="display-1">About ABC Real Central Estate</h1>
        <p class="lead">
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
          pariatur!
        </p>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-4">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href={% url "index" %}> <i class="fas fa-home"></i> Homeless</a>
        </li>
        <li class="breadcrumb-item active">About on</li>
      </ol>
    </nav>
  </div>
</section>

<section id="about" class="py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h2>Perfect Home is in Europe</h2>
        <p class="lead">
          German Hitler ipsum dolor sit,  Italy Mussolin consectetur adipisicing elit. Sunt,
          pariatur!
        </p>
        <img src={% static "img/about.jpg" %} alt="" />
        <p class="mt-2">
          Mark ipsum dolor sit amet consectetur adipisicing elit.
          Perspiciatis esse officia repudiandae ad saepe ex, amet neque quod
          accusamus rem quia magnam magni dolorum facilis ullam minima
          perferendis? Exercitationem at quaerat commodi id libero eveniet
          harum perferendis laborum molestias quia.
        </p>
      </div>
      {% comment %} modify mvp {% endcomment %}
      {% if mvp_realtors %}
      <div class="col-md-3">
        {% for realtor in mvp_realtors %}
        <div class="card">
          <img
            class="card-img-top"
            src={{realtor.photo.url}}
            alt="Seller of the month"
          />
          <div class="card-body">
            <h5 class="card-title">2024 Seller Of The Month</h5>
            <h6 class="text-secondary">{{realtor.name}}</h6>
            <p class="card-text">
              2024 Handsome Mark Lorem tipsum dolor sit amet consectetur adipisicing elit. Omnis
              nesciunt amet, illo itaque similique repellat. content.
            </p>
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</section>

<!-- Work -->
<section id="work" class="bg-dark text-white text-center">
  <h2 class="display-1">2025 Hong Kong Top realtor We serve For You</h2>
  <h4>
    Sahara Desert ipsum dolor sit amet consectetur adipisicing elit. Autem velit
    aperiam, unde aliquid at similique!
  </h4>
  <h2/>
  <a href={% url "listings" %} class="btn btn-secondary text-white btn-lg"
    > View our featured  Listings</a
  >
</section>

<!-- Team -->
<section id="team" class="py-2">
  <div class="container">
    <h2 class="text-center">Fighting Teams</h2>
    <div class="row text-center">
      {% if realtors %}
      {% for realtor in realtors %}
      <div class="col-md-2">
        <img
          src={{ realtor.photo.url }}
          alt=""
          class="rounded-circle mb-5"
        />
        <h4>{{ realtor.name }}</h4>
        <p class="text-success">
          <i class="fas fa-award text-success mb-3"></i> Realtor
        </p>
        <hr />
        <p><i class="fas fa-phone"></i> {{realtor.phone}} </p>
        <p><i class="fas fa-envelope-open"></i>{{realtor.email }}</p>
      </div>
      {% endfor %}
      {% else %}
      <div class="col-md-6">
        <p>No Realtor Available.</p>
      </div>            
      {% endif %}
    </div>
  </div>
</section>

{% endblock %}

templates/partials/_alert.html
{% if messages %}{% comment %} loop messages {% endcomment %}

{% for message  in messages %}
<div class="container" id="message">
<div
    class="alert alert-{{message.tags}}alert-dismissible text-center"
    role ="alert"
    
    <button class="close" type="button"data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
    <button>
        <strong>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error : {% else %} {{message.tags | title}}{% endif %}
        </strong>
        {{message}}
    </div>
</div>




{% end for %}{% endif %}

templates/partials/_footer.html
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
  Copyright &copy;
  <span class="year"></span> BC Real Estate
</footer>